#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
setxkbmap latam &
feh --bg-fill ~/.config/wallpaper.jpg &
picom &

#portapapeles con rofi https://github.com/erebe/greenclip.git  
greenclip daemon &
#tecla super
bspc config pointer_modifier mod1

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           9

bspc config split_ratio          0.56
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
